{{ config(materialized='view') }}
SELECT

SA.SALES_AGENT_ID,

CUST.CUSTOMER_ID,

SA.NAME AS AGENT_NAME,

CUST.CUST_NAME,

SUM((SA.SALEC_COMMISION_PCT*ORD.PURCHASE_AMT)::number(32,2))COMMISION_EARNED

FROM

SALES_AGENT AS SA

INNER JOIN ORDERS ORD

ON ORD.SALES_AGENT_ID =SA.SALES_AGENT_ID

INNER JOIN CUSTOMER CUST

ON CUST.CUSTOMER_ID=ORD.CUSTOMER_ID

GROUP BY 1,2,3,4

ORDER BY 5 DESC